### ISSUE TITLE
Add new icon to admin menu, plugin assets

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#10]
Replace the default calendar icon with ours (if that works).

And the plugin assets: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by nekojira** [comment]
So, for the plugin icon in the plugins directory, should it be a colored one? any other details? this needs to be pushed manually via svn anyway

**Comment by pderksen** [comment]
As discussed in Slack, let's go with green for the plugin directory. Experiment with gradients & background as you see fit.

**Comment by nekojira** [comment]
see: 

https://wordpress.org/plugins/search.php?type=term&q=google+calendar+events

https://wordpress.org/plugins/google-calendar-events/

for current preview

screenshots, lets update when 3.0 lands into directory (needs to match updated readme.txt as well)
