### ISSUE TITLE
Update qTip2 to 3.x & imagesLoaded to 4.x

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#105]
These are both major releases (and imagesLoaded is a dependency of qTip2), so they'll need to be tested thoroughly wherever they're used.

https://github.com/qTip2/qTip2/releases
https://github.com/desandro/imagesloaded/releases

Update bower.json and install via bower update, test minified and unminified files (toggling SCRIPT_DEBUG) and test final build.

**Comment by pderksen** [comment]
@nickyoung87 I'd like you to do this but it can wait until 3.0.14.

**Comment by nickyoung87** [comment]
Posted an issue here: https://github.com/qTip2/bower/issues/1

**Comment by pderksen** [comment]
@nickyoung87 Test out qTip2 3.x manually for now until they fix it.

**Comment by nickyoung87** [comment]
Files updated.

**Comment by nickyoung87** [comment]
@pderksen Tried doing this manually but it breaks the event tooltips. I also found on the website that they only list 2.2.1 as stable so maybe that's the issue here? I guess that maybe the 3.0.2 release isn't a stable release yet?

http://qtip2.com/download

**Comment by pderksen** [comment]
@nickyoung87 Ok with that and bower not being updated lets move it back to 2.x in bower and use that until they stabilize it. If the imagesLoaded update works though and is their stable version at 4.x lets leave that.

**Comment by nickyoung87** [comment]
@pderksen Ok should be good to go then.
