### ISSUE TITLE
Remove Always Enqueue & Disable Scripts advanced options

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#107]
*Updated 1/25/16*

- Remove option `Always Enqueue`
- Remove option `Disable Scripts`
- Keep, but update label 'Disable CSS'
- Update heading to 'Styles`

![image](https://cloud.githubusercontent.com/assets/79667/12559517/64c3cefa-c34a-11e5-9023-26411dd57d0d.png)

See [Give's reasoning for doing so](https://givewp.com/documentation/developers/conditionally-load-give-styles-and-scripts/), and let's follow that.

Reference Simple Pay Lite (& Pro) [commit](https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/commit/f3a05c6928de2f4ea97dc1fbe54fc04da4fa86b0) & [Trello card](https://trello.com/c/NGFpMaLF).

Also ref #87

Post-release add a [code snippet here](https://github.com/moonstonemedia/Simple-Calendar-Library) for conditionally dequeueing & enqueueing scripts.

Add a page to our docs if/when necessary/more requests for explanation.

**Comment by pschfr** [comment]
I saw that @pderksen was planning on adding a code snippet to [moonstonemedia/Simple-Calendar-Library](https://github.com/moonstonemedia/Simple-Calendar-Library), is that available somewhere? I would like to only enqueue my scripts on certain pages, but I am unsure how to go about that.

**Comment by pderksen** [comment]
@pschfr Here you go.

https://github.com/moonstonemedia/Simple-Calendar-Library/blob/master/conditionally-load-scripts-styles.php

Open a PR there if you have any modifications you'd like to see. Thanks!
