### ISSUE TITLE
Add option for 'with_front'

### ISSUE THREAD

**Issue by derekperkins** [moonstonemedia/Simple-Calendar#11]
I have my posts using /blog/ as the prefix, but I don't want my calendar permalinks to be /blog/calendar/...

**Comment by nekojira** [comment]
hey @derekperkins thanks for your previous ticket
would you be keen to try one add-on for Simple Calendar that reads private Google calendars, supports display of attendees, attachments, organizer and can show events colors in calendars? If yes, can I contact you privately at your email address on github to send you a copy? this add-on is not available in a public Github repository ;)
