### ISSUE TITLE
Tooltip shows blank sometimes

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#111]
![tooltip_error](https://cloud.githubusercontent.com/assets/2645164/12586855/2ad49d94-c40f-11e5-9b15-8d947647a55f.png)

**Comment by pderksen** [comment]
I haven't looked into this yet, but things to keep in mind.

- First try #105 to see if simply updating to the next major versions of qTip & imagesLoaded helps.
- Does it happen only when using minified JS? Or when using full JS (SCRIPT_DEBUG on)?
- Are we enqueueing the correct JS files and in the right order?
- Inspect bower & grunt processes for errors. I renamed a few files and such for the last release.

**Comment by nickyoung87** [comment]
@pderksen I tested this out on my Android. It seems like a glitch with the resize call coming from the JS. I commented it out for now and the results are much better.

**Comment by pderksen** [comment]
@nickyoung87 Try #105 (qTip 3.x) to see if it fixes it.

**Comment by nickyoung87** [comment]
@pderksen Tried it after updating qtip2 and it was the same problem.

**Comment by nickyoung87** [comment]
@pderksen When you get a chance please review this screencast (~2:30) and let me know your thoughts.

http://screencast.com/t/5M2QJoSr

Thanks.

**Comment by pderksen** [comment]
@nickyoung87 Might take some going through the qTip docs and examples. Maybe experiment with their 3.x release again. Maybe there's an option or function to call after we do a resize outside of qTip for the dots.

Leave the issue as it was in previous release. Don't think we want to comment out our own resize detection for dots in this release as it may surprise a lot of folks.

**Comment by nickyoung87** [comment]
@pderksen Alright will do. Just to be clear though this is only on the window resize so it won't affect the widgets and such that already are less than the required size to show the dots - those will still work as expected. But it does bring something else up which is if the window is small first and the dots are shown and then the window is resized the dots will still show unless the page is refreshed: http://screencast.com/t/SsK84WIu

But I agree here, maybe we should just leave it as it was for now until we can make sure we don't break anything possibly.

**Comment by pderksen** [comment]
Ok go ahead and uncomment our resize code and slate for the next milestone to look into this more.

**Comment by nickyoung87** [comment]
@pderksen This is updated on `release/3.0.15` now because of the change with #136 

I tested it all out and it looks good on my end for both regular calendar size and responsive sized calendars.
