### ISSUE TITLE
Localization of calendar slug

### ISSUE THREAD

**Issue by olach** [moonstonemedia/Simple-Calendar#12]
I see that the calendar slug is [hard coded](https://github.com/moonstonemedia/Simple-Calendar/blob/master/includes/post-types.php#L190) to `calendar`. Is it possible to have this slug localizable? Either in the translation files or as a setting in admin. What do you think?

**Comment by nekojira** [comment]
is there a standard in wordpress to localize slugs? last time I researched this I didn't find a straightforward way to do it

if you can point me to a source where this is cleared with the best practice to adopt (localization of custom post types), I'd gladly implement it

**Comment by olach** [comment]
According to the WordPress docs, [the slug should be translatable](http://codex.wordpress.org/Function_Reference/register_post_type#rewrite). I have not found an official doc from WordPress on this, but when searching the web, everyone just points to do this the standard way:

    'slug'       => __( 'calendar', 'google-calendar-events' ),

[Another post describes](http://php.quicoto.com/localize-custom-post-type-permalink-wordpress/) how the slug could be set in the admin.

As I said, I have not done this myself. The above solutions seems ok, but I don't know if there are any drawbacks.

**Comment by olach** [comment]
It might be clearer for the translators to have a help text during translation. Something like this:

    'slug'       => _x( 'calendar', 'The calendar slug', 'google-calendar-events' ),

**Comment by nekojira** [comment]
Done, but I'm not entirely sure how solid this is

what if a user switches locale? how are routers, url rewrites and permalinks addressed?

**Comment by nekojira** [comment]
ps I tried the admin method, which I think it's more reliable, but didn't work - if you manage to make it work feel free to issue PR (if you do, code should probably go in includes/admin/post-types.php

**Comment by olach** [comment]
I think it should work, but I'll do a little bit more research. [wpml.org](https://wpml.org) might have some info in their docs.

**Comment by olach** [comment]
[This thread](http://wordpress.stackexchange.com/questions/30021/theme-localization-of-slugs-custom-post-types-taxonomies) has some discussions on this subject. I can't decide which way is the best here.

If a site is going to be multilingual, most probably a multilingual plugin will be used. WPML (the most used multilingual plugin) can [override hardcoded slugs](https://wpml.org/documentation/getting-started-guide/translating-page-slugs/) and make them translatable.

But if a site is going to be in a single language, you probably still want the slug in your own language, but you don't want to install a multilingual plugin for this. Using a gettext function to make the slug translatable should work. Another option is to have the setting specified as a setting under permalink settings. [See this answer](http://wordpress.stackexchange.com/questions/30021/theme-localization-of-slugs-custom-post-types-taxonomies#answer-30723).

So, either translatable slugs using gettext (as you already have done here), or a setting in admin. I don't know which approach is best here.

**Comment by nekojira** [comment]
yeah I actually opened that thread on SO long time ago because I was really unsure of the best practice - but as you can see from the answers there isn't a conclusive answers, just alternatives.

The fact WPML supports translations of slugs shouldn't dictate the solution. It's widely used because there aren't many options in WordPress to handle multilingual content. At some point WordPress might add core support with Babble https://github.com/automattic/babble but it's uncertain. 

I will give another try to the option method, I did try but it didn't work prob I missed out something.

**Comment by olach** [comment]
Oh, didn't see that is was you starting that thread. Small world. :)

I've been thinking of the best approach, and I realize it's not a good solution to go with translatable slugs with gettext. Imagine someone setups a new website with a language different from english. If this plugin doesn't have a translation in that language, then the default slug 'calendar' will be used. But later, if the missing language gets added to this plugin, then the slug gets changed automatically and the original url to the calendar won't work any longer. This might cause some 404:s.

So if you get this option method working, that would be a better solution I think.

**Comment by nekojira** [comment]
I think I will revert this back to hardcoded `calendar`  until the permalink option method is in place
