### ISSUE TITLE
Remove all PHP 5.2 compatibility code

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#120]
Since Google PHP 1.x library requires PHP 5.3.3 or higher.

Make sure it fails gracefully though. See Trello card for more notes.

**Comment by pderksen** [comment]
@nickyoung87 I think this is good, but can you merge `remove-php52-fallback` into the release branch you're working on when you're ready and test (assuming you can temporarily switch to PHP 5.2).

Also, on my Mac at least, I had to wipe out the vendor folder contents and do a new composer update to refresh everything.

Close when it tests out for you, or send back to me if you aren't able to properly test.

**Comment by nickyoung87** [comment]
@pderksen I don't have a way to easily switch PHP versions with XAMPP I don't believe. I will look into it a little bit and then let you know for sure.

**Comment by pderksen** [comment]
Don't sweat it too much. I can test after you're done with all else before release this time. Go ahead and merge it in.

If you see any code that looks like PHP 5.2 fallback code that I missed let me know.
