### ISSUE TITLE
Week view

### ISSUE THREAD

**Issue by fgirardey** [moonstonemedia/Simple-Calendar#124]
Hi guys,

I have a suggestion to enhance this very good plugin. We should have an option to display Google Calendars on week view.

I know it could be very time consuming to develop such a thing, but it can be really useful IMO.

**Comment by pderksen** [comment]
@fgirardey That's a great suggestion, but yes it's a bit of an undertaking. I can't give you a timeline but at some point we will most likely be doing this. Thanks!

**Comment by nickyoung87** [comment]
@pderksen What are your thoughts on this now with FC out? Leave this open or close it?

**Comment by pderksen** [comment]
Agreed. It's in the [Full Calendar](https://simplecalendar.io/addons/fullcalendar/) add-on now so no need here.
