### ISSUE TITLE
Admin edit link

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#125]
We should include a small link to edit the calendar for admins.

**Comment by nickyoung87** [comment]
Seems to work fine. Minor styling to make it a but smaller and on the right hand side under the calendar.

**Comment by nickyoung87** [comment]
@pderksen When you get a chance let me know what you think of this. I did think about putting it in the top right above the calendar instead of bottom right. This would just be because some list views could get extra long and you would have to scroll all the way down to see the link. Let me know what you think though.

**Comment by pderksen** [comment]
@nickyoung87 Yes put it at the top right.

Also make it more consistent with our powered by html. Use `<small>`, `simcal-align-right`, etc.

"E" & "C" should be capitalized to be consistent with WP's "Edit Post", etc.

**Comment by nickyoung87** [comment]
Good call. Will update all of that.

**Comment by nickyoung87** [comment]
Alright this has been adjusted.

**Comment by nickyoung87** [comment]
Use `release/3.0.14` to check this.

**Comment by pderksen** [comment]
@nickyoung87 Looks great!
