### ISSUE TITLE
Deleted calendar event causes php errors.

### ISSUE THREAD

**Issue by petersonca** [moonstonemedia/Simple-Calendar#127]
Deleted an event in my calendar and created another one at a later date. The deleted event is showing up in the response list with a status of "cancelled". Other data in the event is missing, so I get the php error "Trying to get property of non-object in includes/feeds/google.php on line 191".

**Comment by nickyoung87** [comment]
@petersonca Hey thanks for doing this.

I am not able to reproduce this (not saying it isn't happening) so maybe you can provide some help for me to try and see the error. 

- I made an event on Feb 9th
- Cleared cache and loaded calendar and event shows up fine.
- Now I delete the event and create a new event on the 11th.
- Refresh the calendar and get no error but the new event shows correctly.

Maybe I am missing a step somewhere?

Even if I can't reproduce this it will probably make it in to the next release. Could you adjust the code a bit though. Right above the line you added there is already an if statement to continue on under certain criteria. I think you can just add your check there too so we don't have to have multiple ifs doing the same thing. Do you agree?

Thanks again for your contribution it is appreciated!

**Comment by petersonca** [comment]
The problem can be reproduced by creating a recurring event and removing the first occurrence. My simple calendar settings have recurring events set to "Only show first occurrence" and Span set to 1 event. I found that even with this fix, the date shown is the deleted occurrence.  None of these problems happen if I set the Recurring events to "Show all".
