### ISSUE TITLE
Localization of Date and Time

### ISSUE THREAD

**Issue by olach** [moonstonemedia/Simple-Calendar#13]
In Calendar Settings under Advanced, it's possible to configure the Date and Time output. Here in the backend, weekdays and months are correctly localized in my current language (swedish). But in the frontend, they are always in the default english language. Is there a setting for localization of dates somewhere to be found?

I'm using Beta 2.

**Comment by nekojira** [comment]
do you see day names and months in the grid in swedish? 

or is the individual events who don't show dates localized? if that's the case can you overwrite two files file in your installation with the following from the master branch:

https://github.com/moonstonemedia/Simple-Calendar/blob/master/includes/main.php

and

https://github.com/moonstonemedia/Simple-Calendar/blob/master/includes/events/event-builder.php

**Comment by olach** [comment]
No, both in grid and list view, the weekdays and months are in english.

Before I wrote this issue I saw your commit 56ade8bbc3a365eaa4304f68018938eb96d8b861 to `event-builder.php` and tried to update that file, but with no luck. Now, I also updated the `main.php`as you suggested here but with no luck either.

**Comment by nekojira** [comment]
I see another user has this problem http://betel-tulcea.ro/calendar/ (he used to display those dates/days in Romanian fine before, so I guess something happened between beta-1 and beta-2) need to figure out where, probably has to do with Carbon->setLocale

**Comment by olach** [comment]
FYI, I had this issue in beta 1 as well.

**Comment by nekojira** [comment]
check the update

**Comment by nekojira** [comment]
never mind I think this introduces issues somehow...

**Comment by nekojira** [comment]
ok it seems I have used Carbon->setLocale wrong - it only affects certain functions 

here is suggesting to use PHP own setLocale but it's not working with WordPress
http://carbon.nesbot.com/docs/#localization

**Comment by nekojira** [comment]
prob is setLocale seems not to work well with WordPress and I don't understand why date time variables pointed in Carbon example differ from date time codes in PHP date function

**Comment by nekojira** [comment]
a workaround could be using `date_default_timezone_set()` and use WordPress own `date_i18n` function to print dates instead of Carbon (then restore the timezone at the end of a function or view printing those dates, to the one previously set)

**Comment by nekojira** [comment]
Ok I replaced Carbon methods to format date and time with WordPress own `date_i18n` function. 

I think I got a workaround for the timezone handling here:
https://github.com/moonstonemedia/Simple-Calendar/blob/master/includes/abstracts/calendar.php#L757-L763
by setting temporarily the timezone to the one used by the calendar and then restoring the site timezone after it's printed, in this way date and date_i18n should use that timezone when outputting formatted date and time

**Comment by nekojira** [comment]
ps since then I updated the beta-2 zip file available through dropbox download as well

**Comment by olach** [comment]
Tried the updated beta-2 zip file now and localization of Date and Time seems to work now. Thanks a lot!
