### ISSUE TITLE
Grouped calendar showing double events

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#133]
https://wordpress.org/support/topic/double-events-in-grid-view?replies=9

Seems to happen to me so far only when there are a lot of calendars being added. Happening for me when I have 10 calendars added.

**Comment by pderksen** [comment]
User is still having issues. I'm attempting to troubleshoot more with them now.

**Comment by pderksen** [comment]
Confirmed not an issue with our plugin. :)
