### ISSUE TITLE
Update calendar start drop-down section headings

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#134]
I'm not a big fan of the verbiage "Day range", "Week range" etc since you're picking a start point not a range per se.

How about "Specific Day", "Specific Week", etc? Any other ideas?

Existing output:

![image](https://cloud.githubusercontent.com/assets/79667/12956933/4c641d96-cfdf-11e5-9653-b2fd0fc5e21a.png)

**Comment by nickyoung87** [comment]
@pderksen I tried it with "Specific ..." but I didn't really like the way it looked. Plus it seemed confusing since we have the custom option for "Specific Date". I updated it to just remove the "range" part and I think it looks a little better. Let me know what you think of that.

**Comment by pderksen** [comment]
@nickyoung87 Yes nice and clean. I agree. Merge it in then close. Minor verbiage thing so no need to add to the changelog.
