### ISSUE TITLE
Deprecated PHP (on PHP 7)

### ISSUE THREAD

**Issue by spencerm** [moonstonemedia/Simple-Calendar#136]
( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Browser has a deprecated constructor in /srv/www/gomyd.com/current/web/app/plugins/google-calendar-events/vendor/cbschuld/browser.php/lib/Browser.php on line 38

**Comment by nickyoung87** [comment]
@spencerm Thanks for pointing this out, but this is actually an issue with the Browser.php library. It looks like someone else opened an issue for them also: https://github.com/cbschuld/Browser.php/issues/42

**Comment by pderksen** [comment]
@nickyoung87 Let's go ahead and address this at some point soon. Doesn't look like https://github.com/cbschuld/Browser.php is getting maintained much these days. We may need to fork it or find another open fork that is getting maintained. We're also running PHP 7 on our demo site already. :)

**Comment by nickyoung87** [comment]
@pderksen It looks like we can do this pretty easily with composer too. We would just need to point it to the fork we have. https://getcomposer.org/doc/05-repositories.md#vcs

Do you want me to try giving this a shot?

**Comment by pderksen** [comment]
@nickyoung87 Sure give it a shot. But in the end whichever is easiest. Small libraries that aren't updated all too often are fine outside of composer as well, like we did with `wp-requirements`. You can experiment a bit on this though.

**Comment by nickyoung87** [comment]
@pderksen Alright this should be good to go now. Did a little testing and no errors. There were issues with the System Report at first and now there is not so it should all be good.

**Comment by pderksen** [comment]
@nickyoung87 Tests out for me locally on PHP 5.3. Also used for the shortcode copy tooltip based on OS. Just remove the commented out code in the load() function and close.
