### ISSUE TITLE
Update qTip2 to 3.x

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#139]
Splitting this off since we updated imagesloaded on the other issue but this still needs to be done. Original issue is #105

**Comment by nickyoung87** [comment]
Ok I am going to leave this issue open so we don't lose track of it since #105 is closed. I tried updating the files manually but it just didn't work. Thought before it could have been because of the bower thing but I also found this: http://qtip2.com/changelog

Looks like the release is marked in GH but there is not an official changelog release for it so I am wondering if it is not ready yet. Will keep an eye on it.

**Comment by pderksen** [comment]
@nickyoung87 Please test this out for 3.0.17 to see if something is still off. Identify specifics if there are still issues. 3.x was released in Dec 2015 so I don't to get too far behind.

**Comment by nickyoung87** [comment]
@pderksen Can you point me to where you find that 3.x was released?

**Comment by pderksen** [comment]
https://github.com/qTip2/qTip2/releases

Not sure the bower command for checking on major releases. I'm sure there is one though.

**Comment by nickyoung87** [comment]
@pderksen I tried adding this in and it just doesn't want to work. No qtips popup and no error messages or anything - just plain doesn't work for some reason.

**Comment by pderksen** [comment]
We'll address as needed down the road or if more updates come out.

**Comment by nickyoung87** [comment]
No longer using qTip from bower so I am going to close this. See also https://github.com/moonstonemedia/Simple-Calendar/issues/163
