### ISSUE TITLE
Events ending at midnight

### ISSUE THREAD

**Issue by olach** [moonstonemedia/Simple-Calendar#14]
When trying out Beta 2 I encountered a situation where an event ended at midnight.

    Friday 16 October 19:30 - 00:00

IMHO I would rather see this as:

    Friday 16 October 19:30 - 24:00

For an end time after midnight, it should be like `19:30 - 00:01`. 24:00 should only be used for a time to end on exactly midnight.

Note 1: This suggestion is for the 24h clock. For a 12h clock with am/pm I do not know the best practice to print out time.

Note 2: This is only a suggestion, and I'm open to discuss this. Other people might have other opinions. And if it requires too much work, then wait with this for a later version update.

**Comment by nekojira** [comment]
I know and agree with you but that's how I get the event from Google or Carbon (the library used here to parse dates). And midnight has been a pain for many reasons. (When outputting calendars sometimes PHP considers 00:00 on the next day, sometimes on the end of the day before, I added/subtracted some second to events that start around this edge to be on the safe side). 

If you have a solution for this please feel free to issue some PR.

**Comment by olach** [comment]
I understand that this can be a pain to deal with. As I wrote, this is nothing you should prioritize at this point. Better focus to ship v3 out of beta first. :)

**Comment by nekojira** [comment]
hei @olach, would you be keen to try one add-on for Simple Calendar that reads private calendars, supports display of attendees, attachments, organizer and can show Google events colors in calendar? if yes, could I have an email address to share with you the package? this is not available on Github on public repositories ;)

**Comment by olach** [comment]
Sure. You can contact me on: ola.christensson [at] grandpublic.se
