### ISSUE TITLE
Events with 12:00 am end time duplicate

### ISSUE THREAD

**Issue by boblmartens** [moonstonemedia/Simple-Calendar#143]
With a calendar where an event ends at 12:00 am, it will duplicate in a list form (show both on March 3 and March 4 for example) and out of order as well.

Example can be found here:

https://mlc-wels.edu/fitness-center/calendar/fitness-center/

**Comment by nickyoung87** [comment]
We will look into this as soon as we can. Thanks!

**Comment by pderksen** [comment]
@boblmartens Is this still happening for you with the current version?

**Comment by boblmartens** [comment]
Just tested and, no, it is not happening anymore.

**Comment by pderksen** [comment]
@boblmartens Great thanks for letting us know!
