### ISSUE TITLE
Fatal error with Carbon

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#152]
https://wordpress.org/support/topic/fatal-error-class-carboncarbon-after-migration?replies=10

https://wordpress.org/support/topic/carbon-issues?replies=1

**Comment by nickyoung87** [comment]
@pderksen I am going to push this to a lower priority. I reread through the support issues and it seems like this is related to a composer install of the plugin and possibly a wp-cli install of WordPress. There are not a lot of issues that pop up with this either. I would rather focus on some other items for the 3.1.0 release for now until we have time to test more in depth the methods above.

**Comment by pderksen** [comment]
Closing due to age & low priority.
