### ISSUE TITLE
Header not updating dates correctly (list view)

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#153]
https://wordpress.org/support/topic/simple-calendar-the-navigation-arrows-work-not-correctly

**Comment by nickyoung87** [comment]
Possibly related: https://wordpress.org/support/topic/possible-bug-in-navigation-bar-in-list-view?replies=2

Could be a different issue though.

**Comment by pderksen** [comment]
Previously posted in wrong project...

On my wife's site:
http://www.derksenphotography.com/schedule/

Discussed in Slack here:
https://moonstonemedia.slack.com/archives/simple-cal/p1461019522000065

Would prefer disallowing next navigation when there are <10 items in list (what it currently set to).

Screenshots of settings in Slack.

**Comment by nickyoung87** [comment]
@pderksen Ok so this is not technically a bug I don't think, but we will definitely need to figure out better ways to make this work. I say it's technically not a bug because the calendar is using "Today" as the start date, which as of this writing) is in May, so the calendar heading shows May because of that. 

We don't want that to happen though, of course, so I think we need to outline some different scenarios here and make our navigation "smarter".

**Comment by pderksen** [comment]
@nickyoung87 Gotcha. Why does the "next" arrow and letting you navigate next work though when there are no events left?

**Comment by nickyoung87** [comment]
@pderksen Because we removed that pretty close to after the 3.x release because so many people were having navigation issues. The code might just be hidden in there or maybe I can dig up the old issue(s) and we can take a look.

**Comment by nickyoung87** [comment]
https://github.com/moonstonemedia/Simple-Calendar/issues/60
