### ISSUE TITLE
Static calendar label update

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#156]
To be clearer, the label should say "Yes (hide navigation arrows)". Even though the tooltip says this I think it helps at a glance.

![image](https://cloud.githubusercontent.com/assets/79667/14444497/c1367ba0-fffa-11e5-9e00-dbd890404072.png)

**Comment by nickyoung87** [comment]
@pderksen Another simple change here so I just did this directly to the release/3.1.0 branch.
