### ISSUE TITLE
qTip arrow alignment is off when viewing events on mobile

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#163]
Ref https://github.com/moonstonemedia/Simple-Calendar-FullCalendar/issues/42

**Comment by nickyoung87** [comment]
Summary of recent Slack discussion:

- Positioning is correct, but when viewport limits are hit the arrow should be hidden.
- Happens in core plugin as well as combined with FC.

![image](https://cloud.githubusercontent.com/assets/79667/14962174/53aefcfc-1052-11e6-9b6f-a5364f4fe18d.png)

**Comment by pderksen** [comment]
@nickyoung87 Maybe we should be setting the z-index property of the event bubble triangle differently? Just ran across this.

https://github.com/moonstonemedia/Simple-Calendar/blob/f936054bef4d2ae6dc1ffaccdda5bc0a99323945/assets/css/sass/calendars/_default-calendar-grid.scss#L179-L212

**Comment by nickyoung87** [comment]
@pderksen That find of yours was exactly what we needed. This is looking much better now on both desktop and mobile. So this fix is actually a combination of a couple things:

- Removing the CSS you pointed to.
- Ditching the bower version of qTip and creating our custom version with the tip/positioning added in. (from the download options directly from the qTip site)

I did test it with the bower version and it didn't work correctly. The arrow will now align itself under the event or it will not show an arrow if it won't line up (on mobile for instance).

**Comment by pderksen** [comment]
@nickyoung87 Looks good!
