### ISSUE TITLE
Move "Powered by" option to individual calendars

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#165]
Move this from general settings:

![image](https://cloud.githubusercontent.com/assets/79667/15152306/a1aa97b2-1689-11e6-86dd-54faa8a4804d.png)

to individual calendar settings.

It can go at the bottom of Appearance > Misc.
Omit the "Show some love" heading.
Label can say "Yes, show some love" instead.
Tooltip can remain the same unless something looks out of place.

Default to unchecked per WP standards. No need to do an upgrade routine.

**Comment by nickyoung87** [comment]
@pderksen This should be good now.
