### ISSUE TITLE
Month names not being setup for i18n by us

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#171]
https://wordpress.org/support/topic/translations-of-month-names?replies=2

So I think we may just be basing these strings off the default locale of the site, but I need to look further when time permits.

**Comment by nickyoung87** [comment]
So this is actually because we use the `date_i18n` function.  I am not sure if I consider this a bug really since it will automatically pick up the locale the website is in. See the comment from Otto here for more:

https://developer.wordpress.org/reference/functions/date_i18n/

**Comment by pderksen** [comment]
Fixed with #220 I believe.
