### ISSUE TITLE
List View not working correctly

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#176]
There seems to be some major issues with the list view. I will be using this as a main issue for all of the ones I find.

Also see: https://github.com/moonstonemedia/Simple-Calendar/issues/131 , https://github.com/moonstonemedia/Simple-Calendar/issues/143 , https://github.com/moonstonemedia/Simple-Calendar/issues/153

Possibly related: https://github.com/moonstonemedia/Simple-Calendar-Google-Calendar-Pro/issues/10 - move issue to this repo if it should belong here.

First additional issue I am reporting here is this image below. The current day is May 26th, but it is showing dates from before that when it should not be.

![list-issues](https://cloud.githubusercontent.com/assets/2645164/15598097/25ff12b0-2394-11e6-9833-c02248e774a3.png)

Calendar Start: Today
Earliest Event: 1 Month before
Latest Event: 1 year after
Span: 1 week
Expand Multi: No, display on all days of event up to current day (list view only)

**Comment by pderksen** [comment]
@nickyoung87 Added this to your description: Possibly related: https://github.com/moonstonemedia/Simple-Calendar-Google-Calendar-Pro/issues/10 - move issue to this repo if it should belong here.

**Comment by nickyoung87** [comment]
@pderksen I think the new issue you linked there is also the same as this one: https://github.com/moonstonemedia/Simple-Calendar/issues/153

**Comment by nickyoung87** [comment]
@pderksen Ok something interesting I have discovered. This is an issue in PHP 5.3.5 but not in PHP 5.6.11. There must be some kind of logic in the older PHP that is not done correctly, so if I can pinpoint that then hopefully we can resolve this. Since I was running 5.6.11 for so long it would explain why I was not able to reproduce a lot of these list errors that users would talk about.

**Comment by nickyoung87** [comment]
https://bugs.php.net/bug.php?id=51184

**Comment by nickyoung87** [comment]
@pderksen Ok I can't really think of anything alternate to do here, but going by the very last line on the PHP bug report: "VC6 is very old, outdated and not supported anymore, it's easy enough and free to upgrade to newer builds." I am not sure if we should even worry about it. It could just be because I have an older version of XAMPP and that is what was bundled with it. Based on that statement I would assume most hosting providers will not be running the VC6 version since it is old (and it was considered "old" on that post that was posted 4 years ago).

Considering this closed.
