### ISSUE TITLE
Timestamp/date showing incorrect in header when there are no events

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#186]
For some reason it is showing epoch time. Timestamp must be wrong when there are no events. Need to make sure it still displays the correct date.

Necessary at all? Ref #187

**Comment by pderksen** [comment]
Looks funky with just one event also (to me). Maybe think this through as well if folks need.

![image](https://cloud.githubusercontent.com/assets/79667/16243652/2cfd7c5a-37ad-11e6-8454-46921e8a1dac.png)

**Comment by nickyoung87** [comment]
@pderksen This one is officially good now I think.

**Comment by pderksen** [comment]
@nickyoung87 This one and the duplicate heading issue fixed recently test out for me.
