### ISSUE TITLE
HTML in Description not rendering

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#19]
Even with `html="yes"` attribute the `[description]` shortcode is not processing the HTML.

**Comment by nickyoung87** [comment]
@pderksen I really wanted to get this one in the next update. I just fixed it and I think it looks good now. If you are testing the before and after you can check November 9th, 2015 Class B on the Class Schedule calendar as that has HTML output in it.

**Comment by pderksen** [comment]
@nickyoung87 Works great. Merge it in.

**Comment by nickyoung87** [comment]
@pderksen Merged to dev. Closing.

**Comment by livingos** [comment]
This isn't quite working as it did pre v3. 

Images inside the html do not display. The tag <img> appears but its attributes (src, alt etc) get stripped out meaning no image is shown.

**Comment by livingos** [comment]
Scrub that. Turned out the html did not have space between alt and src tags. Possible new version of plugin is more fussy.
