### ISSUE TITLE
event-title no longer supports markdown

### ISSUE THREAD

**Issue by crookedneighbor** [moonstonemedia/Simple-Calendar#204]
Was it intentional for the title tag to no longer support markdown parsing? If so, why?

**Comment by nickyoung87** [comment]
In the earlier version of the plugin it was supported but needed an additional plugin to even make the markdown work so we decided to remove that dependency with the 3.x rewrite.

If you really really need that functionality you can still get the legacy version of the plugin from here: https://wordpress.org/plugins/legacy-google-calendar-events/

The GitHub for that project is here: https://github.com/moonstonemedia/WP-Google-Calendar-Events
