### ISSUE TITLE
Add "Add to Google Calendar" link tag.

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#209]
So visitors can easily add public events to their own calendars.

See this code snippet for starters. It's in JS but probably convert to PHP.
https://github.com/carlsednaoui/add-to-calendar-buttons/blob/master/ouical.js#L14-L31

Other resources:
http://stackoverflow.com/questions/10488831/link-to-add-to-google-calendar

**Comment by pderksen** [comment]
@nickyoung87 Please test from branch `add-to-gcal-link` thoroughly and report back. I'm testing with and without one or both add-ons, with or without locations, descriptions, etc. Some events all day and some not. Basically a bunch from our demo calendar.

**Comment by nickyoung87** [comment]
@pderksen Looks good to me!
