### ISSUE TITLE
Multiple shortcodes on the same page cause script loading issues

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#21]
Loading a list view and a grid view calendar on the same page with shortcodes will cause only one of the scripts to be loaded.

For example only `default-grid.css` will be loaded which will cause the list to appear unrendered.

**Comment by pderksen** [comment]
Not quite ready and will discuss on Slack.

**Comment by nickyoung87** [comment]
@pderksen This is fixed in 3.0.5 correct.
