### ISSUE TITLE
Date headers change when paging in list view (inconsistent start date on page 1)

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#213]
I have not been able to reproduce this but maybe you can @pderksen

wp.org support forum thread listing:

https://wordpress.org/support/topic/list-view-date-changes-after-using-arrows-to-navigate/
https://wordpress.org/support/topic/date-instability-when-using-navigation-arrows/
https://wordpress.org/support/topic/first-date-in-list-view-wrong/?replies=7

**Comment by nickyoung87** [comment]
Another report: https://wordpress.org/support/topic/date-instability-when-using-navigation-arrows/

**Comment by pderksen** [comment]
Can't repeat either. Need to get their setup and calendar IDs.

**Comment by pderksen** [comment]
Public calendar ID for one user: stroudcameraclub@gmail.com

Can't repeat locally yet. Listing add'l threads above.

**Comment by pderksen** [comment]
Thought it might be PHP 5.3, but I was able to repeat on PHP 5.6 locally.

Culprit here is Advanced > Timezone > Events source default.

**Comment by pderksen** [comment]
Updated http://docs.simplecalendar.io/timezone-settings/ as well.

**Comment by pderksen** [comment]
Still happening when setting to custom timezone (i.e. Berlin).

**Comment by pderksen** [comment]
Reference #216 going forward.
