### ISSUE TITLE
List View Expand Multi-Day Event options not all working correctly

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#215]
Looks like the events are not showing if they are in the future unless you have the first option to show all events set.

**PD Correction** (from your comment below): It appears to actually only happen on the last option for multi-day events: "No, display on all days of event up to current day (list view only)".

If you use the demo calendar you can see it with the event "Rock Mayhem".

**PD:** Also noticed with "DJ Night" when it spans multiple days sometimes.

Was mentioned here and I did a quick test to confirm: https://wordpress.org/support/topic/list-display-multiple-days-events/

**Comment by nickyoung87** [comment]
Reported from an HS ticket just now also.

**Comment by nickyoung87** [comment]
@pderksen Here is a screencast of the problem: http://screencast.com/t/bFv6E6KCJ

It appears to actually only happen on the last option for multi-day events: "No, display on all days of event up to current day (list view only)".

**Comment by pderksen** [comment]
@nickyoung87 Please test `issue/215` branch for me on this.

**Comment by nickyoung87** [comment]
@pderksen This looks like it is working now to me. I didn't test on any events midway through though. I just ran the same test as I did before to find out the issue originally.

**Comment by pderksen** [comment]
Ok closing and will be in next release.
