### ISSUE TITLE
Refactor so we don't use date_default_timezone_set() anywhere.

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#216]
Using it is most likely the source of some of our timezone bugs (i.e. #213), but the bigger issue is that we probably shouldn't be using it. `date_default_timezone_set()` is a PHP function that WP ignores and sets to 'UTC' and does offset calculations from there.

https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L52-L53

Update: The Google API client also calls `date_default_timezone_set('UTC')` in their tests.

https://github.com/google/google-api-php-client/blob/master/tests/bootstrap.php

From other calendar plugins I looked at it is never used in their codebases.

- https://vip.wordpress.com/documentation/vip-development-tips-tricks/use-current_time-not-date_default_timezone_set/
- https://weston.ruter.net/2013/04/02/do-not-change-the-default-timezone-from-utc-in-wordpress/
- https://taupecat.com/blog/2010/10/22/using-time-in-your-wordpress-plugin/

Test calendar IDs from users:

- stroudcameraclub@gmail.com
- v0fc4sdjuhc4jiuh3bcarc58mc@group.calendar.google.com
- adminwp@pcsg.fr

Main wp.org thread to post fixes and get beta testers from:
https://wordpress.org/support/topic/list-view-date-changes-after-using-arrows-to-navigate/

**Comment by nickyoung87** [comment]
@pderksen 

Tested and mostly looks ok but as per user response on the forums I tried out these:

[start-time] and [end-time] and those do not show the correct time:

http://screencast.com/t/cKCrMTu0

Looks like they are off by 12 hours.

**Comment by pderksen** [comment]
Yep I forgot to test with tags other than `[when]`. Looks like we need to test thoroughly with the others. Here's what I'm using as the event template now. Add to it if I missed anything.

<strong>[title]</strong>

when: [when]
start-date: [start-date]
start-time: [start-time]
start-human: [start-human]
end-date: [end-date]
end-time: [end-time]
end-human: [end-human]
duration: [duration]

**Comment by pderksen** [comment]
Not getting it locally so far.

Tested PHP 5.3.x through PHP 7.0.x.

Tested timezone settings `Custom - Auckland`, `Site default (America/Los Angeles)`, `Event source default`.

**Comment by pderksen** [comment]
date_i18n() calls combined with offset timestamps were also an issue as they didn't work with varying daylight savings changes at different times of the year in different timezones.
