### ISSUE TITLE
Network error (GET http://h/?ver=3.1.4 net::ERR_NAME_NOT_RESOLVED)

### ISSUE THREAD

**Issue by tomy91** [moonstonemedia/Simple-Calendar#217]
Posted this few days earlier on [Wordpress Support page](https://wordpress.org/support/topic/network-error-get-httphver3-1-4-neterr_name_not_resolved/).

Version 3.1.5 doesn't fix this problem. Only difference it now shows **?ver=3.1.5** instead:
`GET http://h/?ver=3.1.5 net::ERR_NAME_NOT_RESOLVED`

**Comment by pderksen** [comment]
@tomy91 Thanks for sending this in.

Please see my reply to your wp.org thread AND the issue posted here in GitHub at #206.

Since it will be low priority for us if you have any inclination to look into it and have a solution please feel free to submit a PR or code snippet here. Thanks.
