### ISSUE TITLE
Add option for less-styled compact list

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#22]

**Comment by nickyoung87** [comment]
@pderksen Ok this is added in now, but I want to make a few more changes to it to maybe make it a little more "compact". Probably just some CSS to reduce the sizing of certain items like the heading etc.

**Comment by pderksen** [comment]
@nickyoung87 Looking good so far. Agreed the heading could shrink a bit as the default rule. LMK if you want me to take a stab at this since I'm adjusting CSS right now anyway.

**Comment by nickyoung87** [comment]
@pderksen Sure go ahead and do that since you are in there anyway and I am on something else right now.

**Comment by pderksen** [comment]
@nickyoung87 Made some adjustments in `compact-list-heading` branch. Merge into your hide heading feature to make sure they work together.

If I left anything out you were wanting to still change size-wise go for it.

**Comment by nickyoung87** [comment]
@pderksen Awesome, looks good here. Thanks.
