### ISSUE TITLE
Fix for indented, numbered list for events?

### ISSUE THREAD

**Issue by Makosak** [moonstonemedia/Simple-Calendar#235]
I'm helping out with a website, and a strange issue came up with when we updated to a new calendar feed. The google calendar feed is correct -- I checked different potential views, including agenda, at Google Embeddable Calendar Helper to confirm there was no issue from the data streaming side. But using the Simple-Calendar list view, each event is indented with a number. The numbers don't progress; each is no. 1. The setting is identical to a different calendar that already works, as well as the previous feed. I've selected different features on and off to troubleshoot, and changed timezone default, per tips on the forum here, to no avail. I can't find any tips about this from either data streaming or plugin side, perhaps because the search terms are common enough to link to unrelated issues. I *haven't* pulled the calendar feed raw with an ajax request or whatnot, yet, and hoping I don't have to set that up. (Time is limited!)

Any ideas? Really odd, and hopefully it's something obvious I'm missing. Website accessed here: http://stapostleschool.com/ (see middle panel for calendar issue). You can find the feed from there.

**Comment by nickyoung87** [comment]
@Makosak 

Please go through this first to rule out any possible conflicts: http://docs.simplecalendar.io/troubleshooting-theme-plugin-widget-conflicts/

It seems likely to me that this has something to do with how your theme is styling the list elements used to build the calendar list view.

**Comment by Makosak** [comment]
Correct, got it -- it's a theme conflict. Thanks!
