### ISSUE TITLE
Shortcode's wp_enqueue_style does not work in Grid view

### ISSUE THREAD

**Issue by cliffordp** [moonstonemedia/Simple-Calendar#258]
Hi. I am the author of https://wordpress.org/plugins/tk-event-weather/

I'm building an integration with your calendar plugin, and it's gone fine thus far.

Everything works as expected in List View:
![image](https://cloud.githubusercontent.com/assets/1812179/23443977/f11226e8-fdf7-11e6-88cd-8ceb032b007c.png)

However, my shortcode's use of `wp_enqueue_style` doesn't work (the CSS files do not load anywhere in the page source) when using the calendar's Grid View.

If I direct-edit (just to test) https://github.com/moonstonemedia/Simple-Calendar/blob/3.1.9/includes/calendars/views/default-calendar-grid.php#L180 to add the following:
```
			'tkeventw' => array(
				'src'   => '/wp-content/plugins/tk-event-weather/css/tk-event-weather.css',
				'media' => 'all',
			),
			'climacons' => array(
				'src'   => '/wp-content/plugins/tk-event-weather/includes/vendor/climacons/climacons-font.css',
				'media' => 'all',
			),
```

then it displays nicely in Grid View, too:
![image](https://cloud.githubusercontent.com/assets/1812179/23443968/e4a908d6-fdf7-11e6-88b2-33a66dc4ae3f.png)

So, here's where I'm at (please understand I've never before used your plugin except for this 1 day that I wrote this add-on):
* I do not see that `styles` method having a filter
* I did see https://github.com/moonstonemedia/Simple-Calendar/blob/3.1.9/includes/assets.php#L81 action but should that really be necessary -- or maybe a different hook in that file is advisable?
* I do not see a way to detect if I'm in List or Grid view (to then force doing something, or to _not_ do something)
* This may be related to https://github.com/moonstonemedia/Simple-Calendar/issues/208 and maybe even https://github.com/moonstonemedia/Simple-Calendar/issues/166

Thanks so much for your help! :)

**Comment by cliffordp** [comment]
Hmmm, interestingly, it's now working in Grid view without any hacking of Simple Calendar's plugin files. Any thoughts?

**Comment by nickyoung87** [comment]
@cliffordp Sorry for the late reply here. Maybe it was just a caching issue at first?

**Comment by cliffordp** [comment]
I did my darndest to avoid that (plus I was on localhost so probably had caching disabled anyway), but no issues since... thanks for checking in.

Note: hijacking this topic since I've got your ear and wasn't sure how else to get in touch about it... https://docs.simplecalendar.io/google-api-key/ is outdated.

P.S. In trying to build add-ons for various calendars, I appreciate your coding compared to some other calendar plugins! ;)

Thanks!

**Comment by nickyoung87** [comment]
> In trying to build add-ons for various calendars, I appreciate your coding compared to some other calendar plugins! ;)

Haha thanks, but I can't take credit for that. Most of the coding done for this plugin was by another developer @unfulvio 

> Note: hijacking this topic since I've got your ear and wasn't sure how else to get in touch about it... https://docs.simplecalendar.io/google-api-key/ is outdated.

Thanks I will add that to our list of things to check.

I will go ahead and close this for now, but if you experience more problems then please feel free to re-open and let me know.
