### ISSUE TITLE
Balloon text empty (intermittent) after page resize

### ISSUE THREAD

**Issue by davedawkins** [moonstonemedia/Simple-Calendar#261]
You can see this effect on the demo page for Simple Calendar itself:

    https://demo.simplecalendar.io/grid-view/

Hover over the events, and you see full descriptions. I am using Chrome on Windows 10. Now resize the window vertically, say to half size, something significant.

Now, several (but maybe not all) of the events show an empty description.

**Comment by nickyoung87** [comment]
Hi please see #188 and add any additional information there. 

Thanks!

**Comment by davedawkins** [comment]
No additional information for me to add, but I see there's a workaround I
can try by patching the JS.
