### ISSUE TITLE
Better default styling for grid cells that aren't dates ("day-void" cells) 

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#27]
Trying to make it more consistent with styles like the default WP calendar widget.

![image](https://cloud.githubusercontent.com/assets/79667/11156397/86ccb18e-8a00-11e5-9b87-350522e1c098.png)

Currently, ours:

![image](https://cloud.githubusercontent.com/assets/79667/11156409/9dd688e6-8a00-11e5-983b-11174a34f468.png)

1st get to:

![image](https://cloud.githubusercontent.com/assets/79667/11156427/bab67ff2-8a00-11e5-83d3-62ce43fe3162.png)

Eventually:

![image](https://cloud.githubusercontent.com/assets/79667/11156446/d6b91bec-8a00-11e5-92f7-4b68528572a3.png)

Test on light & dark themes, regular & mobile views.

**Comment by pderksen** [comment]
@nickyoung87 Think I got this all the way (on `dev`). Test and close when you can.

**Comment by nickyoung87** [comment]
@pderksen Looks fine to me. Nice work.
