### ISSUE TITLE
Style Issues with Enfold

### ISSUE THREAD

**Issue by boblmartens** [moonstonemedia/Simple-Calendar#3]
I am getting this with the styles on my site using the Enfold theme:

http://beta.mlc-wels.edu/calendar/

Any idea what I can try to get it fixed?

**Comment by nekojira** [comment]
I don't think it was a style issue. But I did update the beta (you can re-download from the same link). It has a minor change (last commit here), it's safe to overwrite your current installation.

**Comment by boblmartens** [comment]
Just updated, and whatever happened, that fixed it. Thanks!
