### ISSUE TITLE
Hover issue on responsive grid view.

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#32]
Currently you cannot hover over the dots on the event day and have the details show up. Some user's are requesting that they be able to do this rather than have it be forced to be clicked.

**Comment by nickyoung87** [comment]
@pderksen Ok so there was a line in the JS that forced it into click for "mobile", but obviously we aren't actually checking for mobile but rather the size of the screen/container. Now no matter if it is responsive or regular view it will just use what the option is set as in the settings. I tested this with `hover` enabled on mobile Android (Chrome & FireFox) as well as an iPhone 6 in chrome on iOS 9.2 and did not have any problems with it there. 

I think if user's do start to have issues with the hover being enabled then we can have them just try changing it to click for that calendar anyway.

**Comment by pderksen** [comment]
Yeah let's see what they come back with.
