### ISSUE TITLE
PHP Version check bug?

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#36]
https://wordpress.org/support/topic/cant-be-activated-thinks-php-is-old-ver?replies=8#post-7670466

**Comment by pderksen** [comment]
@nickyoung87 Looks like it was solved for the original poster, so maybe check with `jpgoguen` and close this and the support thread.

**Comment by nickyoung87** [comment]
Closing this. Still no reply from the other user on WP yet, but fixed for the original poster and those are the only 2 instances I have heard of that issue.
