### ISSUE TITLE
Description should not output a div

### ISSUE THREAD

**Issue by olach** [moonstonemedia/Simple-Calendar#4]
I'm using v3.0 beta 1.

The shortcode for the event description outputs a div element:

    <div class="simcal-event-description">...</div>

But since the text editor in WP automatically inserts a p element on every new line, the div element is placed inside this p element:

        <p><div class="simcal-event-description">...</div></p>

This is not valid html [according to the spec](http://stackoverflow.com/questions/9852312/list-of-html5-elements-that-can-be-nested-inside-p-element). A div element is not allowed inside a p element. And when inspecting the DOM in the dev tools of a browser you can see that the browser is rendering this as:

    <p></p>
    <div class="simcal-event-description">...</div>
    <p></p>

I encountered this when I needed to set a specific class on the surrounding p element in the text editor. It didn't work since this was the result:

    <p class="my-custom-class"></p>
    <div class="simcal-event-description">...</div>
    <p></p>

I would suggest using span element instead of a div element for the output of these shortcodes.

I read in the another issue that you are planning to implement theme templates support for developers. That sounds like a better solution to build custom calendars. But I guess that the shortcode style needs to be around for the non developers.

**Comment by nekojira** [comment]
That's correct, the default template had a markup problem. I fixed this but will leave the description wrapped with `<div>` tag just no longer in the paragraph so it's no longer invalid.

The reason that description shouldn't be in paragraph itself is that it may contain HTML, which could include also block tags like `<div>` - therefore `<span>` wouldn't be suitable to wrap such content. WordPress content editor supports HTML tags including `<div>`. 

Unfortunately there is not a fit-for-all solution. Plan is to continue supporting the current tag system but eventually providing alternatives such as a WYSIWYG editor and theme templates support.

Thank you for reporting this and feel free to submit more bug reports, PR or feedback.

**Comment by nekojira** [comment]
ps if you have a better solution feel free to submit your opinion - I think the problem here is the possibility of HTML markup in description...

**Comment by olach** [comment]
I don't think I have a better solution. Part of the problem is that the WP content editor automatically inserts tags (h1..h6, p etc). Maybe it would be better to not use the standard content editor, and instead use a regular text box, that doesn't automatically insert tags?

**Comment by nekojira** [comment]
Well, there's the HTML tab, but yet it automatically inserts HTML as you point out. 

Problem is, there are current users of legacy versions (before 3.0) that have been using the WordPress content editor for this and I've seen many with some heavy markup (with the HTML tab). Perhaps copying this content during the plugin update to a post meta and then creating the a textarea as you say, but then many would complain of lack of TinyMCE controls. So it should include those somehow. By that point I think it's worth creating an ad-hoc visual editor for Simple Calendar. 

It's worth exploring for the next iteration though.

**Comment by olach** [comment]
I understand the difficulty here. A visual editor or theme templates would be a good next step.

**Comment by nekojira** [comment]
yup, plugin has a bit of technical debt but hopefully can move things forward
