### ISSUE TITLE
Error after updating: Fatal error</b>:  Class 'WP_Requirements' not found in google-calendar-events.php

### ISSUE THREAD

**Issue by L-S-J** [moonstonemedia/Simple-Calendar#40]
<br />
<b>Fatal error</b>:  Class 'WP_Requirements' not found in <b>/home/fossilfreeca/www/www/wp-content/plugins/google-calendar-events/google-calendar-events.php</b> on line <b>46</b><br />

**Comment by pderksen** [comment]
Did you get this trying to run from the source from this repo?

If so, you may need to run the composer commands as outlined here:
https://github.com/moonstonemedia/Simple-Calendar/blob/master/contributing.md

**Comment by L-S-J** [comment]
@pderksen Thanks for the response. No, I just updated the plug-in and now I get this error every time cron runs.

**Comment by pderksen** [comment]
@L-S-J Strange. If you download the latest from https://wordpress.org/plugins/google-calendar-events/ and FTP upload or reinstall the plugin does that help?

**Comment by pderksen** [comment]
@unfulvio Any ideas here he could try?

**Comment by pderksen** [comment]
@L-S-J What do you mean by running cron? wp-cron or regular cron?

**Comment by L-S-J** [comment]
@pderksen, reinstalling doesn't help. I mean regular cron. 

Here's what I find around line 46 of the file referenced by the error:

// Check plugin requirements before loading plugin.
$this_plugin_checks = new WP_Requirements(
	'Simple Calendar',
	plugin_basename( __FILE__ ),
	array(
		'PHP'       => '5.3.0',
		'WordPress' => '4.0.0',
	)
);

I'm running PHP 5.5.26 and WordPress 4.3.1.

**Comment by pderksen** [comment]
Not sure what to do here. No one else is reporting this issue.

Could it be cron is executing something that it shouldn't?

**Comment by gsf** [comment]
Also seeing this issue when deploying with [WP-CLI](http://wp-cli.org/). Running fine in the regular WordPress environment, and we've had no trouble running WP-CLI with the plugin pre-3.0. 

Maybe https://github.com/unfulvio/wp-requirements isn't being included in the command line environment? 

See this recent build for the error message: 
https://travis-ci.org/CityOfPhiladelphia/phila.gov/builds/92986082

**Comment by pderksen** [comment]
@gsf You are correct. This repo currently does not include dependencies in source and needs to run composer and such to include everything as you pointed out in the last reference. It looks like cron and WP-CLI don't do this automatically.

Here are our contributing instructions:
https://github.com/moonstonemedia/Simple-Calendar/blob/master/contributing.md

If you have any suggestions let us know. Thanks.

**Comment by gsf** [comment]
As you can see in the build we're installing this plugin with composer via wpackagist. I would think when brought in this way it would include dependencies. 

If the dependencies are not included, why don't we see this error in the regular WordPress environment?

**Comment by pderksen** [comment]
Unsure here, but we'll look into implementing a release build here in the repo at some point, probably starting with these resources:

https://github.com/blog/1547-release-your-software
https://www.npmjs.com/package/grunt-github-releaser

For now I guess a workaround is just running `grunt build` and taking the build folder from there (which is what's pushed to wordpress.org).

**Comment by L-S-J** [comment]
Thank you @apderksen and @gsf for looking into this. Can you please give instructions for the work around? I would really like to fix the issue so we can keep using this plug-in.

**Comment by pderksen** [comment]
@L-S-J I just updated a few composer items. I'm not real familiar with WP-CLI, composer and packagist yet but I just added `composer/install` to the project in the `composer-install` branch if you could try pointing to that.

@gsf Not sure if this helps you with your project as well.

**Comment by nickyoung87** [comment]
Any luck with the latest changes guys?

**Comment by gsf** [comment]
We ended up vendoring our plugins so we're not relying on composer anymore (problem solved!), but from my conversation in wp-cli/wp-cli#2241 it appears wp-requirements would need to be added to the top level composer.json.

**Comment by pderksen** [comment]
Noting latest wordpress.org support topics referencing this issue:

https://wordpress.org/support/topic/fatal-error-class-wp_requirements-not-found?replies=3
https://wordpress.org/support/topic/plugin-not-compatible-with-civicrm-profiles?replies=7

**Comment by pderksen** [comment]
Moving it out of Composer for now.

**Comment by pderksen** [comment]
@nickyoung87 Close when 3.0.13 is released and you've had a chance to respond to the two forum topics linked.
