### ISSUE TITLE
Make always enqueue option enabled by default

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#42]
Needs to work for all new installs and any upgrades from 2.x+

**Comment by nickyoung87** [comment]
@pderksen Ok I think this is working now correctly. Go ahead and test it if you want and then let me know if you have any issues.

**Comment by nickyoung87** [comment]
Actually there might be an issue here for existing installs. It will still add the option for them so I will need to tweak this to check for some other known option to let us know if the plugin is previously installed before running the default.

**Comment by nickyoung87** [comment]
@pderksen Ok now this should be fine. Added an additional check.

**Comment by pderksen** [comment]
@nickyoung87 Works great on a fresh install (used WP DB reset plugin). I'll trust that you're not *disabling* it for upgrades by accident. Please test if you haven't, then merge to dev.
