### ISSUE TITLE
Scripts not being enqueued correctly on CPT view.

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#43]

**Comment by nickyoung87** [comment]
@pderksen This should be good but after you check it out you can let me know if you see anything on your side or not. On branch `cpt-enqueue`

**Comment by pderksen** [comment]
@nickyoung87 Tests out for me. Merge it into dev and we can prep a release.

**Comment by nickyoung87** [comment]
@pderksen Merged to dev so I am going to close this issue now.
