### ISSUE TITLE
Multi-Day All Day events show on an extra day.

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#44]
https://wordpress.org/support/topic/multiple-days-wrong?replies=1

**Comment by nickyoung87** [comment]
Fix for this here: https://github.com/moonstonemedia/Simple-Calendar/commit/0a46d5b43fbdcf14e83e63e33f99bce80d390a04

**Comment by nickyoung87** [comment]
@pderksen This should be good now if you want to test here is a calendar ID with some multi-day events of various types.

bdie61f4i6in20t90quskqt7ig@group.calendar.google.com

**Comment by pderksen** [comment]
@nickyoung87 Closing but I'd like to follow up in email or slack to lay out the detailed rules and scenarios for this.
