### ISSUE TITLE
Doesn't look right in Firefox

### ISSUE THREAD

**Issue by boblmartens** [moonstonemedia/Simple-Calendar#5]
I have a grid view that is not showing up properly in Firefox (only). Same place as before: beta.mlc-wels.edu/calendar.

Any ideas would be greatly appreciated!

**Comment by nekojira** [comment]
Hi, thanks was aware of that

likely just a CSS problem related to min-height on some table cell element originally set to even the heights of cells with varying amount of events (or no events) in them - perhaps can be removed but needs testing

it's going to be fixed before release just didn't have time to look into that yet

if you find a fix please feel free to suggest changes (as long as it doesn't break other browsers in turn)

**Comment by boblmartens** [comment]
Happy to hear you are aware of it. We are still in development, so I'm just making sure we have our ducks in a row as well.

Thanks!

**Comment by nekojira** [comment]
As far as I know there should be another glitch with safari/mobile with tooltips - prob related to qtip js more than css

**Comment by boblmartens** [comment]
I think there is, but that part I haven't tested as much yet. I will get it on my list of things to do.

**Comment by boblmartens** [comment]
What is the issue with the tooltips in Safari?

**Comment by nekojira** [comment]
that commit seem to have sorted it, but there's a bit to review in style and markup still

if you want to try this from the git repository, mind you need to run composer first

**Comment by boblmartens** [comment]
I'll wait for the next release and then take a look. Thanks!
