### ISSUE TITLE
Last event in calendar list isn't printed.

### ISSUE THREAD

**Issue by petersonca** [moonstonemedia/Simple-Calendar#51]
This was happening to me and others, so I debugged it and found a really simple fix.

For the discussion, see [https://wordpress.org/support/topic/last-event-always-dropped](https://wordpress.org/support/topic/last-event-always-dropped)

I've got the pull request ready to go (one character change). :)

**Comment by nickyoung87** [comment]
Thanks a bunch. Added in for 3.0.6 release.
