### ISSUE TITLE
Qtip image showing in top left corner

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#55]
https://wordpress.org/support/topic/widget-grid-view-unwanted-image?replies=2#post-7715750

**Comment by nickyoung87** [comment]
@pderksen Used CSS to hide this extra qtip triangle showing. I know we don't like to use `!important` but since it is using inline styling I put it in there.

**Comment by pderksen** [comment]
@nickyoung87 That's fine for cases like this.
