### ISSUE TITLE
Human event builder code not working correctly?

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#59]

**Comment by nickyoung87** [comment]
Needs more testing.

**Comment by nickyoung87** [comment]
@pderksen Added the "before" and "After" text depending on the context of the time. Should be ok now I think.

**Comment by nickyoung87** [comment]
Re-opening this to change the text. Change to "ago" and "from now" per request https://wordpress.org/support/topic/start-human-tag-changes-in-3012?replies=3

It makes more sense to me this way too.

**Comment by pderksen** [comment]
@nickyoung87 Whatever wording seems pretty standard with other date/"time ago" libraries let's do here.

**Comment by nickyoung87** [comment]
@pderksen Changed to "ago" / "from now". I took a look at the Carbon library since that's what we use and that is the text they use for their differences like that.
