### ISSUE TITLE
Ability to limit the total number of items in a list view

### ISSUE THREAD

**Issue by boblmartens** [moonstonemedia/Simple-Calendar#6]
I'd love to have the option of restricting not just the number of items on a given day, but a number of items shown overall within a list view. Am I just missing the way to make this possible?

**Comment by nekojira** [comment]
You can make a list using 'events' as span 

Select `list` then go to `appearance` tab, select `events` as span type, then a number of events you want to display per page (this is regardless of time span, but calendar start set in `events` tab still applies)

**Comment by boblmartens** [comment]
I totally missed that. Thanks!

**Comment by nekojira** [comment]
let me know if it works right and even if it does, but there's still something not intuitive in the admin settings panel

**Comment by boblmartens** [comment]
It works as I would think. The problem for me is that I didn't read down the entire list and saw the time spans first.
