### ISSUE TITLE
Text note about Google API key for Pro

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#66]
http://screencast.com/t/sZjrWUpY3GF

While this is technically correct, it might be a little misleading since you still have to setup an OAuth key. 

@pderksen Maybe we can come up with better wording somehow for this?

**Comment by pderksen** [comment]
@nickyoung87 Give it a shot. What would you change? (Just enter here for now)

**Comment by nickyoung87** [comment]
@pderksen Maybe this:

`Note: Calendars configured to use the Google Calendar Pro add-on use a different method of authorization.`

**Comment by pderksen** [comment]
@nickyoung87 Yes that works.

**Comment by nickyoung87** [comment]
@pderksen This is updated and should be ok to merge.
