### ISSUE TITLE
UTC Times from WP Settings not transferring correctly to calendar settings timezone select

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#68]
In the WP settings you have 2 options for how you can set the timezone. A string version like "America/Denver" or a UTC version like "UTC-7".

The UTC versions are not transferring correctly to the calendar settings select option for "Site Default". Do using the values from the example above UTC -7 should show America/Denver as the site default, but in this case it is showing up as Los Angeles instead.

**Comment by nickyoung87** [comment]
@pderksen Looks like a function here was using standard time and not daylight savings time. We may need to mark that to look into at some point so we don't have to remember to change that function when the time changes.

**Comment by pderksen** [comment]
@nickyoung87 Sounds important. If it can be straightened out completely now while you're in the middle of things I'd rather it not wait until an impeding time change is coming.

**Comment by nickyoung87** [comment]
Created a new issue for the other fix. Merged this to dev so closing now.
