### ISSUE TITLE
All day events not showing up

### ISSUE THREAD

**Issue by boblmartens** [moonstonemedia/Simple-Calendar#7]
Events that are listed as day-long are not showing up. This one, specifically, is an event that lasts 5 days but has no time attached to it.

**Comment by nekojira** [comment]
please attach here the calendar ID

also, is it showing the first day (start day)?

**Comment by boblmartens** [comment]
Calendar ID: mlc-wels.edu_2702lo7q075j1al4avh85dgi7o@group.calendar.google.com

The first event is not showing up.

**Comment by nekojira** [comment]
is it the event in november? international education week? it does show for me, but you need to tick 'expand multi day events' in default calendar appearance if you want to have it appear on each grid cell for example - the default calendar is a bit basic; compared to previous versions it has at least titles in grid now but it's still a bit simple

**Comment by nekojira** [comment]
uhm actually I found a bug but slightly unrelated

**Comment by boblmartens** [comment]
I'm seeing two issues now:

1) in a list view the all-day events do not show up (even when checking the option to expand to each day)
2) within the grid view, all of the events for the entire week show up on the same day

Here is the calendar in list view that I listed here: http://beta.mlc-wels.edu/international-students/calendar/

Should I just delete it and recreate it?
