### ISSUE TITLE
Welcome screen not displaying at the correct time.

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#74]
Supposed to show right after activation, but it is showing after you make an action after installing/activating it. For example: Fresh install, click "Add New Plugin" and then the screen shows instead of right away.

**Comment by nickyoung87** [comment]
Should be good to go now.

**Comment by pderksen** [comment]
Seemed to work on a fresh install of 3.0.10 after a previous plugin removal (with delete settings checked).

@nickyoung87 Once we get to 3.1.x will the welcome screen show up again (and in the right place) for people after upgrading? I was hoping to re-show it after minor version (not patch) upgrades.

**Comment by nickyoung87** [comment]
@pderksen I believe @unfulvio added the functionality for it to do that also. I did not mess with any of _how_ it works, but just adjusted _when_ it works.
