### ISSUE TITLE
Error: Missing arguments in default calendar grid ajax request

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#76]
https://wordpress.org/support/topic/grid-format-giving-error-missing-arguments-in-default-calendar-grid-ajax-reque?replies=18

**Comment by nickyoung87** [comment]
Still fishing for info here. Seems like it is theme related but it's affecting about 4-6 people now.

**Comment by pderksen** [comment]
@nickyoung87 Since this is JS-related, if you get stuck here let me know and I'll take a look. Would be nice to resolve before the next release.

**Comment by nickyoung87** [comment]
Found out this was an issue with other themes/plugins loading old versions of jQuery. Simple Calendar requires 1.9+ for this function to work correctly. If you come across this issue update your jQuery version to the latest and it should go away.
