### ISSUE TITLE
Boolean Queries not working (OR)

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#77]
https://wordpress.org/support/topic/bug-report-boolean-queries-not-working-or?replies=2

**Comment by nickyoung87** [comment]
@pderksen I looked into this but I really am starting to think it is just not possible. I tried different manipulation of the URL parameters. I actually even tried this on the Google calendar API page where you can OAuth in and test out what the results would be for a certain function and it still returned nothing. I am thinking we might just have to remove this from the documentation on the site since it doesn't seem possible. If you have other thoughts or ideas I would love to hear them first though.

**Comment by pderksen** [comment]
@nickyoung87 Agreed. If searching capabilities only work without operators, then document this and respond accordingly.

**Comment by nickyoung87** [comment]
@pderksen Alright did a few more tests to make sure as well as testing the other stuff on the docs page ( http://docs.simplecalendar.io/google-calendar-search-queries/ ). I removed the parts that are no longer accurate to avoid future confusion for users.

**Comment by pderksen** [comment]
Looks good.
