### ISSUE TITLE
Truncating description issue

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#81]
Doesn't seem to work correctly for a shortcode like this:

`[description html="yes" markdown="yes" limit="45" autolink="yes"]`

When removing the other attributes it seems to work as intended. Maybe there is a conflict between the attributes?

**Comment by nickyoung87** [comment]
Found out it is done on purpose like this:

https://github.com/moonstonemedia/Simple-Calendar/blob/dev/includes/events/event-builder.php#L551-L561

I imagine this is because things can get weird with having to count words if there is HTML in the mix. I also ran a small test with it and when I did the HTML didn't even show up when running it through the limit function.

@pderkesn Any thoughts on this? Do you think we should try to figure out a way to manage both limiting the description and allowing HTML at the same time? Or do you think maybe it's better the way it is designed now?

**Comment by pderksen** [comment]
@nickyoung87 Depends how important this is to users. I'd say if easy use a WP or PHP function to strip out HTML and count if html="yes"? Or if that's not doable explain that the limit attribute includes html/markup characters so they could bump it up say double or whatever so it imposes some kind of limit.

**Comment by nickyoung87** [comment]
@pderksen Ok changed it so the limit doesn't only run as an else to HTML and markdown and also removed the stripping of the tags from the limit count because that was returning the text without the HTML in it anymore. I did a few tests and it seems like if there is HTML in it then it counts each element as a word of it's own. I will add that to the documentation when we go live.

**Comment by pderksen** [comment]
@nickyoung87 Close when added to docs.

**Comment by nickyoung87** [comment]
Updated `limit` text under `description` here: http://docs.simplecalendar.io/event-template-tags/
