### ISSUE TITLE
showing only the first event

### ISSUE THREAD

**Issue by jozwa** [moonstonemedia/Simple-Calendar#91]
i have made 2 views of the calendar, one with al coming up, en one with only the first one.
This are them all:
<img width="304" alt="schermafbeelding 2016-01-03 om 18 24 44" src="https://cloud.githubusercontent.com/assets/16528064/12079822/a21e8d12-b247-11e5-8693-38c0701ca265.png">
[link to the website](http://smmb.nl/calendar/rijdag/)

This is one event:
<img width="294" alt="schermafbeelding 2016-01-03 om 18 24 18" src="https://cloud.githubusercontent.com/assets/16528064/12079826/b14bb9e0-b247-11e5-83ba-835e934dcc36.png">
[link to the website](http://smmb.nl/calendar/een_rijdag/)

but why is it showing not the first one?

It looks also that there is something wrong with the Maximum Events function.
This are to accepted options:

1. The value 0 but it will result in 2500 after saving and the view is the value 1
2. The value 1 that is what you see, i take the middle one
3. The value 2 wil result `mei` and `juli` in my case. I can't explain that.
4. Everything else wil change to 2500 after losing focus on the input field.

**Comment by nickyoung87** [comment]
So what setting are you referring to here? Max events?

**Comment by jozwa** [comment]
sorry for the delay.
Yes that function does it wrong in my case.
Do you need more info?

**Comment by nickyoung87** [comment]
@jozwa First if you haven't already please update to the latest release (3.0.13). After that make sure you are setting the "Span" option to a value higher than 1 and also the same for your "Maximum Events" option. If you are still having trouble then please share your calendar feed settings with me and I will see if I spot anything out of place.

**Comment by jozwa** [comment]
i just did that. update everything that is possible.
i clear all the cache and i made a new calendar with the same calendar id.
<img width="685" alt="schermafbeelding 2016-02-02 om 19 18 11" src="https://cloud.githubusercontent.com/assets/16528064/12759658/a09249ae-c9e2-11e5-94d3-2a1a273bab32.png">
<img width="752" alt="schermafbeelding 2016-02-02 om 19 18 18" src="https://cloud.githubusercontent.com/assets/16528064/12759660/a1cf0050-c9e2-11e5-91ef-d0c0e6de10b1.png">
<img width="860" alt="schermafbeelding 2016-02-02 om 19 18 36" src="https://cloud.githubusercontent.com/assets/16528064/12759661/a2fd0a44-c9e2-11e5-80c3-ef461c173a4a.png">
<img width="878" alt="schermafbeelding 2016-02-02 om 19 18 44" src="https://cloud.githubusercontent.com/assets/16528064/12759662/a43ab7f8-c9e2-11e5-9e52-ced681e94a6d.png">
<img width="571" alt="schermafbeelding 2016-02-02 om 19 18 50" src="https://cloud.githubusercontent.com/assets/16528064/12759663/a597d626-c9e2-11e5-85e8-f9fb4685ab0b.png">
<img width="348" alt="schermafbeelding 2016-02-02 om 19 19 00" src="https://cloud.githubusercontent.com/assets/16528064/12759665/a6dbecf2-c9e2-11e5-9d1b-0ecac3d16a83.png">
<img width="235" alt="schermafbeelding 2016-02-02 om 19 19 16" src="https://cloud.githubusercontent.com/assets/16528064/12759668/a9f01134-c9e2-11e5-87e5-144c58662f14.png">
<img width="823" alt="schermafbeelding 2016-02-02 om 19 26 53" src="https://cloud.githubusercontent.com/assets/16528064/12759706/f210c198-c9e2-11e5-98e9-da5f393c3f6c.png">

so i don't know anymore
here is de google calendar id for testing yourself
s9jmjh432mqk5asi2cegcqa45s@group.calendar.google.com

**Comment by nickyoung87** [comment]
@jozwa Are those events that are showing up recurring events?

What happens if you put your max events at 2500?

**Comment by jozwa** [comment]
@nickyoung87. I think yes because I made 1 event and repeated every first Wednesday of the month. But I change a few with some notes or moved one to an other day. Is that still recurring?

If I put Max to 2500 I see all events. That is how I create thee page with all events together.

**Comment by nickyoung87** [comment]
@jozwa Ok so try keeping the maximum events at 2500 but change your "Span" option to something like "2 events" and see if that works how you are wanting it to.

**Comment by jozwa** [comment]
Yes that works.
The reason i started this issue is because the way i made it, was fine in version 2.x of the plugin.
Clearly it have to be done different in version 3.x
So than this issue can be closed i think.
Thanks for the support

**Comment by nickyoung87** [comment]
Ah ok sorry about the confusion with the options changing. Glad we were able to get it sorted out for you though.
