### ISSUE TITLE
Show multi-day event on each day it runs (list view)

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#94]
https://wordpress.org/support/topic/multi-day-events-5?replies=17

- We need to show the event on each day that it is happening even if expand multi-day events is not enabled.

- Should only show up on the current day

- Example: Event A runs Mon - Thursday and the calendar is a list view showing next X events. We do not have multi-day events enabled. Event A will show correctly on Monday and not any other day. When viewing the calendar on Tuesday, however, we want our users to know that there is still an all-day long event going on, but currently this will not happen - Event A will not show up. This is where we need to make a change so that Event A will now show up on Tuesday when viewing the calendar on Tuesday, then Wednesday, etc.

**Comment by pderksen** [comment]
Note this was the behavior in GCE 2.4.

**Comment by nickyoung87** [comment]
@pderksen Did a last test on this and it appears to be good going forward as well as users who update. Would like for you to check this out at least a little bit before releasing.

**Comment by pderksen** [comment]
@nickyoung87 As mentioned in Slack I wasn't able to run this branch. LMK when it's ready to test again.

**Comment by nickyoung87** [comment]
@pderksen I was not able to reproduce the error on my side, but looking at what you sent me I believe this last commit should fix the problem.

**Comment by nickyoung87** [comment]
I merged #103 into this for easier testing.
