### ISSUE TITLE
How to add text to a calendar CPT page?

### ISSUE THREAD

**Issue by nickyoung87** [moonstonemedia/Simple-Calendar#98]
This has only been mentioned by 1 person so far so not necessarily a high priority but I thin it is interesting. 

Basically, right now if someone is linking directly to the calendar CPT page they are not able to add page content as well. This is mostly due to the fact that we hijack the editor to use for the event template tags. Maybe this will be a combined enhancement when we work out #50 also.

**Comment by pderksen** [comment]
@nickyoung87 Don't think we can support this one. It's the whole reason for adding calendar shortcodes to posts & pages.

**Comment by nickyoung87** [comment]
Alright sounds good to me. Closing.
